# Generated by Django 3.2.7 on 2021-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='nick_name'),
        ),
    ]
